<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cloud.mmda</groupId>
        <artifactId>mmda-core</artifactId>
        <version>5.0.0</version>
    </parent>

    <artifactId>mmda-core-api</artifactId>
    <name>MMDA Core Api</name>
    <version>5.0.0</version>
    <description>
        MMDA Core Api provides base api controllers.
    </description>

    <dependencies>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-services</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-security</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-data</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-entities</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-metadata</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-caching</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-utils</artifactId>
            <version>${project.version}</version>
<!--            <scope>system</scope>-->
<!--            <systemPath>${mmda.local.repository}/mmda-core-utils/${mmda-core.version}/mmda-core-utils-${project.version}.jar</systemPath>-->
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jdbc</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>32.1.3-jre</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
    </dependencies>
</project>