<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
<!--    <parent>-->
<!--        <groupId>cloud.mmda</groupId>-->
<!--        <artifactId>mmda-core</artifactId>-->
<!--        <version>4.0.0</version>-->
<!--        <relativePath/>-->
<!--    </parent>-->
    <groupId>cloud.mmda</groupId>
    <artifactId>mmda-core-dependencies</artifactId>
    <version>5.0.0</version>
    <name>MMDA Core Dependencies</name>
    <description>MMDA Core Dependencies </description>
    <url>https://www.mmda.cloud</url>

    <packaging>pom</packaging>
    <properties>
        <mmda-core.version>5.0.0</mmda-core.version>
        <mmda.local.repository>C:/Users/${user.name}/.m2/repository/cloud/mmda</mmda.local.repository>
    </properties>
    <!-- see https://github.com/spring-cloud/spring-cloud-release/blob/main/spring-cloud-dependencies/pom.xml-->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-entities</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-utils</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-metadata</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-caching</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-security</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-data</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-messaging</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-services</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.mmda</groupId>
                <artifactId>mmda-core-api</artifactId>
                <version>${mmda-core.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <distributionManagement>
        <repository>
            <id>local-repo</id>
            <url>file://C:/Users/${user.name}/.m2/repository</url>
        </repository>
    </distributionManagement>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.6.0</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <!-- Flatten and simplify our own POM for install/deploy -->
                        <id>flatten</id>
                        <phase>routing-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                        <configuration>
                            <updatePomFile>true</updatePomFile>
                            <flattenMode>bom</flattenMode>
                            <pomElements>
                                <parent>expand</parent>
                                <pluginManagement>keep</pluginManagement>
                                <attributes>keep</attributes>
                                <repositories>remove</repositories>
                            </pomElements>
                        </configuration>
                    </execution>
                    <execution>
                        <id>flatten-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>