<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>mmda-core</artifactId>
        <groupId>cloud.mmda</groupId>
        <version>5.0.0</version>
    </parent>
    <artifactId>mmda-core-services</artifactId>
    <packaging>jar</packaging>

    <name>MMDA Core Services</name>
    <version>5.0.0</version>
    <description>
        MMDA Core Services defines all base domain services.
    </description>

    <dependencies>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-utils</artifactId>
            <version>${project.version}</version>
<!--            <scope>system</scope>-->
<!--            <systemPath>${mmda.local.repository}/mmda-core-utils/${mmda-core.version}/mmda-core-utils-${project.version}.jar</systemPath>-->
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-entities</artifactId>
            <version>${project.version}</version>
<!--            <scope>system</scope>-->
<!--            <systemPath>${mmda.local.repository}/mmda-core-entities/${mmda-core.version}/mmda-core-entities-${project.version}.jar</systemPath>-->
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-metadata</artifactId>
            <version>${project.version}</version>
<!--            <scope>system</scope>-->
<!--            <systemPath>${mmda.local.repository}/mmda-core-metadata/${mmda-core.version}/mmda-core-metadata-${project.version}.jar</systemPath>-->
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-caching</artifactId>
            <version>${project.version}</version>
<!--            <scope>system</scope>-->
<!--            <systemPath>${mmda.local.repository}/mmda-core-caching/${mmda-core.version}/mmda-core-caching-${project.version}.jar</systemPath>-->
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-data</artifactId>
            <version>${project.version}</version>
<!--            <scope>system</scope>-->
<!--            ${mmda.local.repository}/mmda-core-data/${mmda-core.version}/mmda-core-data-${project.version}.jar</systemPath>-->
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-security</artifactId>
            <version>${project.version}</version>
<!--            <scope>system</scope>-->
<!--            <systemPath>${mmda.local.repository}/mmda-core-security/${mmda-core.version}/mmda-core-security-${project.version}.jar</systemPath>-->
        </dependency>
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-file</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!--消息推送依赖-->
        <dependency>
            <groupId>cloud.mmda</groupId>
            <artifactId>mmda-core-messaging</artifactId>
            <version>${mmda-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
        </dependency>
    </dependencies>
</project>